### PR TITLE
Fixed the super() call

### PR DESCRIPTION
**Pull request by cicobalico**
This works for Python 2.7.9 on ubuntu 15.04
do you think this is acceptable?

### CODE REVIEW

**Comment by hadim** [comment]
Hello @cicobalico and thank you for this PR.

Nowdays Python 3 is becoming more and more mainstream and I really don't want to have to use Python 2 features when I can make the code prettier and easier to read with Python 3 only features. I would prefer to not bother with Python 2 compatibility.

Do you think you can switch to Python 3 ?

If your distribution does not have Python 3 I would strongly suggest you to use Anaconda as your main Python distribution for your development : http://conda.pydata.org/docs/install/quick.html

**Comment by hadim** [comment]
In Ubuntu 15.04 Python 3 is already installed so you just have to do execute your code with `python3`. But as I said I would suggest you to use Anaconda.

**Comment by hadim** [comment]
Did you find a way to use Python 3 ?

**Comment by cicobalico** [comment]
Thank you for your help @hadim ,
I did try to run my script under python3 but there are some incompatible libraries and most of my code is old and outdated.
Next time I start from scratch I'll make sure to script in python3
For the time being I wanted to try to adapt your scripts for python 2 in a fork if that is acceptable, but this is my first github contribution experience and I have to say I'm a little lost with all the forking branching merging and PRing.
Any tip/rule I might be missing would be **greatly** appreciated!

**Comment by hadim** [comment]
Well the correction you did in your fork should make `keras-toolbox` works with Python 2. So unless you have a Python 3 compatible code I would suggest you to use your fork.

Ask me if you have any more questions.

**Pull request closed without merging**
